class Constant {
  static String baseUrl = "https://weebs-cf327.uc.r.appspot.com";
  static String apiKey = "wHNFET6Lwp7EAFMkCzOe2oLeEYop0evdo3k2iDGyz2w=";

  static List<String> get genreList => [
        "Action",
        "Adventure",
        "Cars",
        "Comedy",
        "Dementia",
        "Demons",
        "Drama",
        "Historical",
        "Josei",
        "Kids",
        "Magic",
        "Martial Arts",
        "Mecha",
        "Military",
        "Music",
        "Mystery",
        "Parody",
        "Police",
        "Psychological",
        "Romance",
        "Samurai",
        "School",
        "Sci-Fi",
        "Seinen",
        "Shoujo",
        "Shoujo AI",
        "Shounen",
        "Shounen AI",
        "Slice Of Life",
        " Space",
        "Sports",
        "Super Power",
        "Supernatural",
        "Thriller",
        "Vampire",
        "Yaoi",
        "Yuri"
      ];

  static List<String> get seasonList => [
        "Winter 2020",
        "Fall 2019",
        "Summer 2019",
        "Spring 2019",
        "Winter 2019",
        "Fall 2018",
        "Summer 2018",
        "Spring 2018",
        "Winter 2018",
        "Fall 2017",
        "Summer 2017",
        "Spring 2017",
        "Winter 2017",
        "Fall 2016",
        "Summer 2016",
        "Spring 2016",
        "Winter 2016",
        "Fall 2015",
        "Summer 2015",
        "Spring 2015",
        "Winter 2015"
      ];
}
