name: PlayStore Release

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build APK and Create release
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.0.1'
    - run: flutter pub get
    - run: flutter build apk
    - run: flutter build appbundle
    - name: Create a Release in GitHub
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/app/outputs/apk/release/*.apk,build/app/outputs/bundle/release/app-release.aab"
        token: ${{ secrets.TOKEN }}
        tag: ${{ steps.version.outputs.content }}
        commit: ${{ github.sha }}
    - name: Upload app bundle
      uses: actions/upload-artifact@v2
      with:
        name: appbundle
        path: build/app/outputs/bundle/release/app-release.aab
  release:
    name: Release app to Release
    needs: [ build ]
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Get appbundle from artifacts
      uses: actions/download-artifact@v2
      with:
        name: appbundle
    - name: Release app to Release
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJsonPlainText: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
        packageName: com.pain.freeforweebs
        releaseFile: app-release.aab
        track: production
        whatsNewDirectory: distribution/whatsnew