name: Deploy to Play Store
on:
  # Enable manual run
  workflow_dispatch:
    inputs:
      lane:
        description: "Fastlane lane"
        required: true
        default: "production"
        type: choice
        options:
          - production

# Declare default permissions as read only.
permissions: read-all

jobs:
  fastlane-deploy:
    runs-on: macos-latest
    steps:
      # Set up Flutter.
      - name: Clone Flutter repository with stable channel
        uses: subosito/flutter-action@de3cdb9a4b2f535dc0fa0da445a46b10b1bfefc7
        with:
          flutter-version: '3.0.1'
      - run: flutter doctor -v

      # Checkout gallery code and get packages.
      - name: Checkout weebs code
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - run: flutter pub get

      # Setup Ruby, Bundler, and Gemfile dependencies
      - name: Setup Fastlane
        uses: ruby/setup-ruby@72d59482210349c1114eca714b6c5df19fbbec34
        with:
          ruby-version: "2.6"
          bundler-cache: true
          working-directory: android

      - name: Configure Keystore
        run: |
          echo "$PLAY_STORE_UPLOAD_KEY" | base64 --decode > app/upload-keystore.jks
          echo "storeFile=key.jks" >> key.properties
          echo "keyAlias=$KEYSTORE_KEY_ALIAS" >> key.properties
          echo "storePassword=$KEYSTORE_STORE_PASSWORD" >> key.properties
          echo "keyPassword=$KEYSTORE_KEY_PASSWORD" >> key.properties
        env:
          PLAY_STORE_UPLOAD_KEY: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          KEYSTORE_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          KEYSTORE_KEY_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          KEYSTORE_STORE_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
        working-directory: android

      # Build and deploy with Fastlane (by default, to beta track) 🚀.
      # Naturally, promote_to_production only deploys.
      - run: bundle exec fastlane ${{ github.event.inputs.lane || 'production' }}
        env:
          PLAY_STORE_CONFIG_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
        working-directory: android