# This is a basic workflow to help you get started with Actions

name: Release App to Playstore

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
jobs:
  build:
    name: Build & Release
    runs-on: macos-latest
    steps: 
      - name: Checkout Setup
        uses: actions/checkout@v3
      
      - name: Java Setup
        uses: actions/setup-java@v3.5.0
        with:
          distribution: 'temurin'
          java-version: '17'
        
      - name: Flutter action
        uses: subosito/flutter-action@v2.7.1
        with:
          flutter-version: '3.3.2'
          channel: 'stable'
      
      - run: flutter pub get
      
      - name: Signing Key
        id: android_keystore
        uses: timheuer/base64-to-file@v1.1
        with:
          fileName: key.jks
          encodedString: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          
      - name: Create key.properties
        run: |
          echo "storeFile=${{ steps.android_keystore.outputs.filePath }}" > android/key.properties
          echo "storePassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}" >> android/key.properties
          echo "keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}" >> android/key.properties
          
      - name: Building App Bundle
        run: flutter build appbundle --build-number
      
      - name: Releasing app to google play 
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
          packageName: com.pain.freeforweebs
          releaseFiles: build/app/outputs/bundle/release/app-release.aab
          track: production
          status: inProgress
          inAppUpdatePriority: 2
          userFraction: 0.9
          whatsNewDirectory: distribution/whatsnew
          mappingFile: build/app/outputs/mapping/release/mapping.txt
          debugSymbols: build/app/intermediates/merged_native_libs/release/out/lib
          
        
      
      
      
